services:
  app:
    build: .
    ports:
      - "3334:80"
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      - pocketbase

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data

